rem Query 1

SELECT DEPARTMENT.deptid, DEPARTMENT.dname, COUNT(FACULTY.fid)
FROM DEPARTMENT
LEFT JOIN FACULTY
ON DEPARTMENT.deptid = FACULTY.deptid
GROUP BY DEPARTMENT.deptid, DEPARTMENT.dname
ORDER BY DEPARTMENT.dname;

rem Query 2

SELECT FACULTY.fid, FACULTY.fname, FACULTY.deptid
FROM FACULTY
WHERE FACULTY.fid IN (SELECT CLASS.fid
			FROM CLASS
			GROUP BY CLASS.fid
			HAVING COUNT(*) >= ALL (SELECT MAX(COUNT(CLASS.fid))
						FROM CLASS
						GROUP BY fid));

rem Query 3

SELECT STUDENT.deptid, STUDENT.sname, STUDENT.AGE
FROM STUDENT
WHERE STUDENT.snum IN (SELECT snum
				FROM ENROLLED e
				WHERE cname IN (SELECT DISTINCT ENROLLED.cname
							FROM ENROLLED, CLASS,FACULTY, DEPARTMENT
							WHERE dname = 'Computer Sciences' AND FACULTY.deptid = DEPARTMENT.deptid AND CLASS.fid = FACULTY.fid AND ENROLLED.cname = CLASS.cname) AND ROWNUM < 2
				GROUP BY snum);

rem Query 4

SELECT DISTINCT STUDENT.sname, STUDENT.deptid
FROM STUDENT
WHERE STUDENT.snum IN (SELECT ENROLLED.snum
				FROM ENROLLED
				GROUP BY ENROLLED.snum
				HAVING COUNT(*) >= ALL (SELECT COUNT(*)
								FROM ENROLLED e
								GROUP BY e.snum))
UNION
SELECT DISTINCT STUDENT.sname, STUDENT.deptid
FROM STUDENT
WHERE STUDENT.age < 20;

rem Query 5

SELECT STUDENT.snum
FROM STUDENT
WHERE STUDENT.snum IN (SELECT ENROLLED.snum
				FROM ENROLLED
				WHERE ENROLLED.cname IN (SELECT cname
								FROM CLASS
								WHERE cname IN (SELECT cname
											FROM ENROLLED
											GROUP BY cname
											HAVING COUNT(cname) > 2
											))) AND ROWNUM < 2;

rem Query 6

SELECT DISTINCT FACULTY.fname
FROM FACULTY
WHERE FACULTY.fid IN (SELECT CLASS.fid
			FROM CLASS
			GROUP BY CLASS.fid
			HAVING COUNT(CLASS.room) > 2);


rem Query 7

SELECT DEPARTMENT.deptid, AVG(STUDENT.age)
FROM DEPARTMENT
LEFT JOIN STUDENT
ON DEPARTMENT.deptid = STUDENT.deptid
WHERE Department.deptid NOT IN (SELECT d.deptid
				FROM DEPARTMENT d
				WHERE d.dname LIKE 'Management')
GROUP BY DEPARTMENT.deptid
ORDER BY DEPARTMENT.deptid;


rem Query 8

SELECT STUDENT.deptid, STUDENT.sname, STUDENT.AGE
FROM STUDENT
WHERE STUDENT.snum NOT IN (SELECT ENROLLED.snum 
				FROM ENROLLED
				) AND STUDENT.AGE = (SELECT MIN(age)
							FROM STUDENT
							WHERE STUDENT.snum NOT IN (SELECT ENROLLED.snum
							FROM ENROLLED
							));


rem Query 9

SELECT STUDENT.snum
FROM STUDENT
WHERE STUDENT.deptid NOT IN (SELECT FACULTY.deptid
					FROM FACULTY, CLASS
					WHERE FACULTY.fid = CLASS.fid)
ORDER BY snum DESC;

rem Query 10

CREATE VIEW view_temp AS
SELECT cname, count(e.cname) AS ct
FROM ENROLLED e
GROUP BY cname
HAVING COUNT(cname) >= ALL( SELECT MAX(COUNT(cname))
				FROM ENROLLED 
				GROUP BY cname);

SELECT DISTINCT f.fname, vt.CT
FROM FACULTY f, CLASS c, ENROLLED e, view_temp vt
WHERE c.cname = (SELECT cname
			FROM ENROLLED
			GROUP BY cname
			HAVING COUNT(cname) >= ALL( SELECT MAX(COUNT(cname))
							FROM ENROLLED 
							GROUP BY cname)) AND c.fid=f.fid;

DROP VIEW view_temp;





